# Generated by Django 5.2.8 on 2026-05-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255, verbose_name='Філія')),
                ('revision', models.CharField(blank=True, default='', max_length=64, verbose_name='Редакція')),
                ('report_date', models.DateField(verbose_name='Дата')),
                ('site_name', models.CharField(max_length=255, verbose_name='Назва дільниці')),
                ('inspector_full_name', models.CharField(max_length=255, verbose_name='ПІБ перевіряючого (еколог)')),
                ('unit_representative_full_name', models.CharField(max_length=255, verbose_name='ПІБ представника підрозділу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Environmental report',
                'verbose_name_plural': 'Environmental reports',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Підпис')),
                ('image', models.ImageField(upload_to='environmental_reports/photos/', verbose_name='Фото')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.environmentalreport')),
            ],
            options={
                'verbose_name': 'Environmental photo',
                'verbose_name_plural': 'Environmental photos',
                'ordering': ['order_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalNonconformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(verbose_name='№ п/п')),
                ('description', models.TextField(verbose_name='Опис невідповідності')),
                ('corrective_actions', models.TextField(blank=True, default='', verbose_name='Коригуючі дії')),
                ('responsible', models.CharField(blank=True, default='', max_length=255, verbose_name='Відповідальний')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Строк виконання')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformities', to='reports.environmentalreport')),
            ],
            options={
                'verbose_name': 'Environmental nonconformity',
                'verbose_name_plural': 'Environmental nonconformities',
                'ordering': ['order_number', 'id'],
            },
        ),
    ]
