# Generated by Django 5.2.8 on 2026-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalreport',
            name='inspection_form',
            field=models.CharField(blank=True, default='позапланова', max_length=32, verbose_name='Форма перевірки'),
        ),
    ]
