# Generated by Django 5.2.8 on 2026-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_environmentalreport_inspection_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalreport',
            name='expert_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ПІБ експерта'),
        ),
    ]
