# Generated by Django 5.2.8 on 2026-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_environmentalreport_expert_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalreport',
            name='inspector_position',
            field=models.CharField(blank=True, default='Провідний Еколог', max_length=255, verbose_name='Посада перевіряючого'),
        ),
        migrations.AddField(
            model_name='environmentalreport',
            name='unit_representative_position',
            field=models.CharField(blank=True, default='Начальник дільниці', max_length=255, verbose_name='Посада представника підрозділу'),
        ),
    ]
