# Generated by Django 5.2.8 on 2026-05-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_environmentalreport_inspector_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalreport',
            name='expert_position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Посада відповідальної особи'),
        ),
        migrations.AlterField(
            model_name='environmentalreport',
            name='expert_full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ПІБ відповідальної особи'),
        ),
    ]
